name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      docker_password:
        description: 'Docker Hub Password or Token'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: yaokunlin
        password: ${{ github.event.inputs.docker_password }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./app
        push: true
        tags: yaokunlin/twu-app:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kompose/app-deployment.yaml
        kubectl apply -f kompose/app-service.yaml
